channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- bokeh
- cython
- future
- h5py
- ipython
- ipyparallel
- jupyter
- keras
- matplotlib
- nose
- numpy
- opencv
- peakutils
- scipy
- scikit-image
- scikit-learn
- spyder
- tensorflow
- tifffile
- tqdm
