channels:
- conda-forge
- defaults
- menpo
dependencies:
- python=2.7
- tensorflow
- keras
- future
- numpy
- scipy
- ipython
- ipyparallel
- jupyter
- matplotlib
- scikit-image
- scikit-learn
- h5py
- cython
- spyder
- nose
- bokeh
- tqdm
- opencv3
- pip:
  - tifffile
  - peakutils

