package:
  name: constrained_nmf
  version: "0.1"

 
source:
  #git_rev: 0.04
  #git_url: https://github.com/agiovann/Constrained_NMF.git
  #git_tag: 507cac2
  path: .

  
requirements:
  build:
    - python <3
    - setuptools
    - pip 
            
  
  run:
    - python <3
    - numpy
    - scipy
    - ipython
    - matplotlib
    - scikit-learn
    - scikit-image   
    - ipyparallel
    - jupyter 
    - bokeh
    - cvxopt 
    - joblib >=0.8.4
#    - tifffile >=0.7.0        
#    - picos >=1.1.1

 
#test:
#    files:
#      - movies/demoMovie.tif          


about:
  home: http://agiovann.github.io/Constrained_NMF
  license: GPL2
  license_file: LICENSE.txt