package:
  name: constrained_nmf
  version: "0.1"

 
source:
  git_rev: 0.03
  git_url: https://github.com/agiovann/Constrained_NMF.git
 
requirements:
  build:
    - python
    - setuptools
    - numpy
    - ipython
    - scipy
    - matplotlib
    - scikit-learn
    - scikit-image
    - ipyparallel
    - bokeh
    - jupyter
    - scikit-learn        
    - cvxopt

  run:
    - python
 
test:

 
about:
  home: http://agiovann.github.io/Constrained_NMF
  license: GPL2
  license_file: LICENSE.txt