package:
  name: constrained_nmf
  version: "0.1"

 
source:
  #git_rev: 0.03
  #git_url: https://github.com/agiovann/Constrained_NMF.git
  path: ../Constrained_NMF 
requirements:
  build:
    - python <3
    - setuptools
    - pip 
            
#    - tifffile >=0.7.0    
#    - joblib >=0.8.4
#    - pico >=1.1.1
  
  run:
    - python <3
    - numpy
    - scipy
    - ipython
    - matplotlib
    - scikit-learn
    - scikit-image   
    - ipyparallel
    - jupyter 
    - bokeh
    - cvxopt 
#    - tifffile >=0.7.0    
#    - joblib >=0.8.4
#    - pico >=1.1.1

 
test:

 
about:
  home: http://agiovann.github.io/Constrained_NMF
  license: GPL2
  license_file: LICENSE.txt